/**
 * Copyright © 2014 - 2018 Leipzig University (Database Research Group)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.gradoop.common.config;

import java.io.Serializable;

/**
 * Gradoop Accumulo configuration define with its builder
 */
public class GradoopAccumuloConfig implements Serializable {

  /**
   * default zookeeper hosts
   */
  private static final String DEFAULT_ZOOKEEPER_HOSTS = "localhost:2181";

  /**
   * default accumulo instance
   */
  private static final String DEFAULT_ACCUMULO_INSTANCE = "instance";

  /**
   * default accumulo user
   */
  private static final String DEFAULT_ACCUMULO_USER = "root";

  /**
   * default accumulo password
   */
  private static final String DEFAULT_ACCUMULO_PASSWORD = "";

  /**
   * zookeeper hosts
   */
  private String zookeeperHosts = "localhost:2181";

  /**
   * accumulo instance
   */
  private String accumuloInstance = "instance";

  /**
   * accumulo user
   */
  private String accumuloUser = "root";

  /**
   * accumulo password
   */
  private String accumuloPasswd = "";

  public String getZookeeperHosts() {
    return zookeeperHosts;
  }

  public String getAccumuloInstance() {
    return accumuloInstance;
  }

  public String getAccumuloUser() {
    return accumuloUser;
  }

  public String getAccumuloPasswd() {
    return accumuloPasswd;
  }

  /***
   * accumulo configure builder
   */
  public static class Builder {

    /**
     * zookeeper hosts
     */
    private String zookeeperHosts = DEFAULT_ZOOKEEPER_HOSTS;

    /**
     * accumulo instance
     */
    private String accumuloInstance = DEFAULT_ACCUMULO_INSTANCE;

    /**
     * accumulo user
     */
    private String accumuloUser = DEFAULT_ACCUMULO_USER;

    /**
     * accumulo password
     */
    private String accumuloPasswd = DEFAULT_ACCUMULO_PASSWORD;

    /**
     * zookeeper hosts which splits with ','
     * For example:
     * 192.168.1.1:2181,192.168.1.2:2181
     *
     * @param zookeeperHosts zookeeper hosts for accumulo instance
     * @return configure builder instance itself
     */
    public Builder zookeeper(String zookeeperHosts) {
      this.zookeeperHosts = zookeeperHosts;
      return this;
    }

    /**
     * accumulo instance name
     *
     * @param accumuloInstance instance name
     * @return configure builder instance itself
     */
    public Builder acInstance(String accumuloInstance) {
      this.accumuloInstance = accumuloInstance;
      return this;
    }

    /**
     * accumulo user name
     *
     * @param accumuloUser user name
     * @return configure builder instance itself
     */
    public Builder acUser(String accumuloUser) {
      this.accumuloUser = accumuloUser;
      return this;
    }

    /**
     * accumulo password
     *
     * @param accumuloPasswd password
     * @return configure builder instance itself
     */
    public Builder acPasswd(String accumuloPasswd) {
      this.accumuloPasswd = accumuloPasswd;
      return this;
    }

    /**
     * generate configure with builder
     *
     * @return configure generated by builder
     */
    public GradoopAccumuloConfig create() {
      GradoopAccumuloConfig config = new GradoopAccumuloConfig();
      config.zookeeperHosts = zookeeperHosts;
      config.accumuloInstance = accumuloInstance;
      config.accumuloUser = accumuloUser;
      config.accumuloPasswd = accumuloPasswd;
      return config;
    }

  }
}
